name = "WaveRave"
uuid = "8d2a3bad-826d-4e97-b88c-1069f7cd513b"
authors = ["Derrick Chambers <d-chambers@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
