name = "WaveRave"
uuid = "8d2a3bad-826d-4e97-b88c-1069f7cd513b"
authors = ["Derrick Chambers <d-chambers@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
