
echo ""
echo "Creating Mesh For 1 Process"

mkdir outputs
mkdir outputs/plots

mpiexec -n 1 python src/mesher.py 300 500

echo ""
echo "Running Simulation with 1 Process"
echo ""
mpiexec -n 1 python src/run.py 300 500

echo ""
echo "Plotting for 1 process"
mpiexec -n 1 python src/plot.py 300 500 

mv outputs outputs_with_1_process

mkdir outputs
mkdir outputs/plots


echo ""
echo ""
echo "Creating Mesh For 8 Processes"

mpiexec -n 8 python src/mesher.py 300 500
echo ""
echo "Running Simulation with 8 Processes"
echo ""
mpiexec -n 8 python src/run.py 300 500

echo ""
echo "Plotting for 8 processes"
mpiexec -n 8 python src/plot.py 300 500 


mv outputs outputs_with_8_process

mkdir outputs
mkdir outputs/plots


echo "Check the plots generated by running with 1 and 8 process and see if they are same"


