
echo ""
echo "Creating Mesh For 1 Process"

mkdir outputs
mkdir outputs/plots

mpiexec -n 1 python src/mesher.py 300 500

echo ""
echo "Running Simulation with 1 Process"
echo ""

mpiexec -n 1 python src/run.py 300 500

echo ""
echo "Plotting for 1 process"
python src/plot.py 300 500 1

mv outputs outputs_with_1_process

mkdir outputs
mkdir outputs/plots


echo ""
echo ""
echo "Creating Mesh For 8 Processes"

mpiexec -n 8 python src/mesher.py 300 500
echo ""
echo "Running Simulation with 8 Processes"
echo ""
start=date
mpiexec -n 8 python src/run.py 300 500
end=date
echo $start $end | awk '{print $2-$1}'

echo ""
echo "Plotting for 8 processes"
python src/plot.py 300 500 8


mv outputs outputs_with_8_process

mkdir outputs
mkdir outputs/plots


echo "Check the plots generated by running with 1 and 8 process and see if they are same"

python test_int.py 300 500 1 8


